"""Construcción de los controles de la ventana principal."""
import tkinter as tk
from tkinter import ttk
from .arrastrar import USE_DND, DND_FILES
from .estilos import BG_PRIMARY, BG_SECONDARY, BORDER_COLOR, ACCENT_BLUE

def construir_interfaz(self):
    self.padding = {'padx': 16, 'pady': 8}
    self.header_frame = ttk.Frame(self.root)
    self.header_frame.configure(style='TFrame')
    self.header_frame.grid(row=0, column=0, sticky='ew', padx=16, pady=(16, 8))
    self.header_frame.grid_columnconfigure(1, weight=1)
    self.actions_frame = ttk.Frame(self.header_frame)
    self.actions_frame.configure(style='TFrame')
    self.actions_frame.grid(row=0, column=0, sticky='w')
    ttk.Button(self.actions_frame, text='📁 Añadir', style='Add.TButton', command=self.seleccionar_pdfs).grid(row=0, column=0, padx=(0, 8))
    ttk.Button(self.actions_frame, text='🗑 Limpiar', style='DangerMinimal.TButton', command=self.limpiar_lista).grid(row=0, column=1, padx=(0, 8))
    self.btn_combinar = ttk.Button(self.actions_frame, text='🚀 Combinar', command=self.combinar, style='CompactPrimary.TButton')
    self.btn_combinar.grid(row=0, column=2)
    self.btn_configuracion = ttk.Button(self.header_frame, text='⚙️', command=self.abrir_configuracion, style='Config.TButton', width=3)
    self.btn_configuracion.grid(row=0, column=2, sticky='e')
    self.separator1 = ttk.Separator(self.root, orient=tk.HORIZONTAL)
    self.separator1.grid(row=1, column=0, sticky='ew', padx=16, pady=(0, 16))
    self.config_frame = ttk.Frame(self.root)
    self.config_frame.configure(style='TFrame')
    self.config_frame.grid(row=2, column=0, sticky='ew', **self.padding)
    self.config_frame.grid_columnconfigure(1, weight=1)
    ttk.Label(self.config_frame, text='Tipo de fondo:', style='Secondary.TLabel').grid(row=0, column=0, sticky='w', padx=(0, 12))
    self.combo_tipo_fondo = ttk.Combobox(self.config_frame, textvariable=self.tipo_fondo_var, values=['Acreditado', 'No Acreditado'], state='readonly', width=20)
    self.combo_tipo_fondo.grid(row=0, column=1, sticky='w')
    self.separator2 = ttk.Separator(self.root, orient=tk.HORIZONTAL)
    self.separator2.grid(row=3, column=0, sticky='ew', padx=16, pady=16)
    self.pdfs_frame = ttk.Frame(self.root)
    self.pdfs_frame.configure(style='TFrame')
    self.pdfs_frame.grid(row=4, column=0, sticky='ew', **self.padding)
    self.pdfs_frame.grid_columnconfigure(0, weight=1)
    self.style.configure('PDFTitle.TLabel', font=('Segoe UI', 11, 'bold'), foreground=ACCENT_BLUE, background=BG_PRIMARY)
    self.pdfs_title = ttk.Label(self.pdfs_frame, text='Archivos PDF', style='PDFTitle.TLabel')
    self.pdfs_title.grid(row=0, column=0, sticky='w', pady=(0, 8))
    self.list_container = ttk.Frame(self.pdfs_frame)
    self.list_container.configure(style='TFrame')
    self.list_container.grid(row=1, column=0, sticky='ew', pady=(0, 12))
    self.list_container.grid_columnconfigure(0, weight=1)
    self.scroll = ttk.Scrollbar(self.list_container, orient=tk.VERTICAL)
    self.listbox_pdfs = tk.Listbox(self.list_container, width=70, height=6, yscrollcommand=self.scroll.set, bd=1, relief='solid', highlightthickness=2, highlightcolor=ACCENT_BLUE, highlightbackground=BORDER_COLOR, bg=BG_SECONDARY, selectbackground=ACCENT_BLUE, selectforeground='white', font=('Segoe UI', 9))
    self.scroll.config(command=self.listbox_pdfs.yview)
    self.listbox_pdfs.grid(row=0, column=0, sticky='ew', padx=(0, 2))
    self.scroll.grid(row=0, column=1, sticky='ns')
    if USE_DND:
        self.listbox_pdfs.drop_target_register(DND_FILES)
        self.listbox_pdfs.dnd_bind('<<Drop>>', self.drop)
    self.listbox_pdfs.bind('<Button-3>', self.mostrar_menu_contextual)
    self.listbox_pdfs.bind('<Button-2>', self.mostrar_menu_contextual)
    self.status_frame = ttk.Frame(self.root)
    self.status_frame.configure(style='TFrame')
    self.status_frame.grid(row=5, column=0, sticky='ew', padx=16, pady=(8, 16))
    self.status_frame.grid_columnconfigure(1, weight=1)
    self.label_status = ttk.Label(self.status_frame, text='0 archivos', style='Secondary.TLabel')
    self.label_status.grid(row=0, column=0, sticky='w')
    self.label_output_mode = ttk.Label(self.status_frame, text='', style='Secondary.TLabel', width=34, anchor='e')
    self.label_output_mode.grid(row=0, column=2, sticky='e')
    self.progress_bar = ttk.Progressbar(self.status_frame, orient=tk.HORIZONTAL, mode='determinate')
    self.progress_bar.grid(row=1, column=0, columnspan=3, sticky='ew', pady=(4, 0))
    self.progress_bar.grid_remove()
    self.label_progress = ttk.Label(self.status_frame, text='', style='Secondary.TLabel', wraplength=700, justify='left')
    self.label_progress.grid(row=2, column=0, columnspan=3, sticky='w')
    self.combo_fondo = self.tipo_fondo_var
